### ISSUE TITLE
Logo Ideas

### ISSUE THREAD

**Issue by ken-scarf** [scarf-sh/tie#15]
I think a good guideline for a logo is something that we can easily turn into slack/discord/skype/twitch emoji. We also want to stick to the neckwear theme.

### Background:
This library generates a haskell implementation from an openapi spec.

### References:
Open API Spec Logo
* https://avatars3.githubusercontent.com/u/16343502?v=3&s=200

Once we get consensus on the ideas here we'll polish it.

**Comment by ken-scarf** [comment]
![0F1D6284-11C1-40DF-A9C8-A1F8E2D423B8](https://user-images.githubusercontent.com/92234785/158049716-da7b5de5-dc7d-4ae7-9920-b3302e0da12b.png)

**Comment by aviaviavi** [comment]
We can get design to help out here!

**Comment by ken-scarf** [comment]
That would be awesome!

**Comment by alexbiehl** [comment]
Closing for now.
